# Generated by Django 6.0.6 on 2026-07-03 08:25

import django.core.validators
import students.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=50, validators=[students.validators.validate_student_name])),
                ('roll_number', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, validators=[students.validators.validate_roll_number_pattern])),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('phone', models.CharField(max_length=10, validators=[students.validators.validate_phone_number])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('department', models.CharField(choices=[('CSE', 'Computer Science Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering'), ('AIML', 'Artificial Intelligence & Machine Learning'), ('CSM', 'Computer Science & Engineering (AI & ML)'), ('CSD', 'Computer Science & Engineering (Data Science)'), ('IT', 'Information Technology')], max_length=10)),
                ('year', models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')])),
                ('section', models.CharField(choices=[('A', 'Section A'), ('B', 'Section B'), ('C', 'Section C'), ('D', 'Section D')], max_length=1)),
                ('cgpa', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('attendance', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('admission_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
